-- CreateTable
CREATE TABLE "app_config" (
    "id" TEXT NOT NULL,
    "shopName" TEXT NOT NULL,
    "ownerName" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "website" TEXT,
    "npwp" TEXT,
    "nib" TEXT,
    "ppn" DECIMAL(65,30) NOT NULL DEFAULT 0.11,
    "isPpnEnabled" BOOLEAN NOT NULL DEFAULT true,
    "priceIncludesTax" BOOLEAN NOT NULL DEFAULT false,
    "currency" TEXT NOT NULL DEFAULT 'IDR',
    "invoicePrefix" TEXT NOT NULL DEFAULT 'INV',
    "invoiceCounter" INTEGER NOT NULL DEFAULT 0,
    "showLogoOnReceipt" BOOLEAN NOT NULL DEFAULT true,
    "footerNote" TEXT,
    "lowStockThreshold" INTEGER NOT NULL DEFAULT 5,
    "logoUrl" TEXT NOT NULL,
    "bannerUrl" TEXT NOT NULL,
    "faviconUrl" TEXT,
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Jakarta',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "updatedBy" TEXT,

    CONSTRAINT "app_config_pkey" PRIMARY KEY ("id")
);
